import Image from 'next/image';

export const About = () => {
  return (
    <section className="w-full">
      <div className="w-full px-[72px] pt-[60px]">
        <div className="w-[216px]">
          <h2 className="uppercase text-[40px] leading-none font-black font-RightGrotesk mb-4">
            <span>Story that started with</span>{' '}
            <span className="text-accentColor"> one simple ape</span>
          </h2>
        </div>
        <ul className="flex flex-col items-center gap-y-[72px] mb-[40px]">
          <li>
            <p className="uppercase text-right text-base">
              WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
              THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
            </p>
          </li>
          <li>
            <p className="uppercase text-sm text-center leading-[1.16]">
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </p>
          </li>
        </ul>
      </div>
      <div className="w-full flex-col flex items-center">
        <div className="mx-auto px-[72px]">
          <Image
            src="/images/about/apeAboutMobile.png"
            width={216}
            height={292}
            alt="ape"
            className=""
          />
        </div>
        <div className="bg-accentColor w-full py-2">
          <div className="min-w-[218px]">
            <p className="uppercase text-4xl text-center font-black font-RightGrotesk leading-none tracking-tight">
              HAVE NO LIMITS
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};
